[2022-12-17 15:22:19,920] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: scheduler_dag.data_generator_task manual__2022-12-17T15:22:14.881386+00:00 [queued]>
[2022-12-17 15:22:19,986] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: scheduler_dag.data_generator_task manual__2022-12-17T15:22:14.881386+00:00 [queued]>
[2022-12-17 15:22:19,989] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-17 15:22:19,991] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-17 15:22:19,997] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-17 15:22:20,093] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): data_generator_task> on 2022-12-17 15:22:14.881386+00:00
[2022-12-17 15:22:20,106] {standard_task_runner.py:52} INFO - Started process 261 to run task
[2022-12-17 15:22:20,125] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scheduler_dag', 'data_generator_task', 'manual__2022-12-17T15:22:14.881386+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/scheduler.py', '--cfg-path', '/tmp/tmpyoat5244', '--error-file', '/tmp/tmpkaud5dzh']
[2022-12-17 15:22:20,129] {standard_task_runner.py:77} INFO - Job 5: Subtask data_generator_task
[2022-12-17 15:22:20,382] {logging_mixin.py:109} INFO - Running <TaskInstance: scheduler_dag.data_generator_task manual__2022-12-17T15:22:14.881386+00:00 [running]> on host 6661800004c3
[2022-12-17 15:22:20,553] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scheduler_dag
AIRFLOW_CTX_TASK_ID=data_generator_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-17T15:22:14.881386+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-17T15:22:14.881386+00:00
[2022-12-17 15:22:20,558] {python.py:175} INFO - Done. Returned value was: None
[2022-12-17 15:22:20,593] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=scheduler_dag, task_id=data_generator_task, execution_date=20221217T152214, start_date=20221217T152219, end_date=20221217T152220
[2022-12-17 15:22:20,676] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-17 15:22:20,788] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
